  on:
    push:
      branches:
        - main
  jobs:
    build:
      permissions:
        id-token: 'write'
        contents: 'read'
      name: "Build new release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - uses: actions/cache@v4
          with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        - run: bun install
        - run: bun run build
        - name: 'Run gcp auth'
          uses: 'google-github-actions/auth@v2'
          with:
            service_account: ${{secrets.SVC_ACC}}
            workload_identity_provider: ${{secrets.WORKLOAD_IDP}}
        - name: 'Run cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
            version: '>= 363.0.0'
        - name: 'Run sync assets'
          run: 'gsutil -m rsync -R -d ./dist gs://darkm-blog-sa-prd'
