  on:
    push:
      branches:
        - main
  jobs:
    build:
      permissions:
        id-token: 'write'
        contents: 'read'
      name: "Build new release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - uses: actions/cache@v4
          with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        - run: bun install
        - run: bun run build
        - id: 'gcp-auth'
          uses: 'google-github-actions/auth@v2'
          with:
            token_format: 'access_token'
            project_id: 'darkmdev'
            service_account: 'github@darkmdev.iam.gserviceaccount.com'
            workload_identity_provider: 'projects/242066346830/locations/global/workloadIdentityPools/darkm-pool/providers/github-action-blog'
        - id: 'upload-dist'
          uses: 'google-github-actions/upload-cloud-storage@v2'
          with:
            path: './dist'
            destination: 'darkm-blog-sa-prd'
            parent: false
